unit Pokedex.Styles.Constants;

interface

const
  BUTTON_COLOR = $003A1EA1;
  BUTTON_COLOR_HOVER = $00564AEA;
  BUTTON_COLOR_DISABLE = $00B5B5B5;
  FONT_COLOR_DISABLE = $00868686;

  BUTTON_NAV_COLOR = $001C1611;
  BUTTON_NAV_COLOR_HOVER = $00392D22;

//  HP_COLOR =
//  HP_COLOR_HOVER =
//  ATK_COLOR =
//  ATK_COLOR_HOVER =
//  DEFENSE_COLOR =
//  DEFENSE_COLOR_HOVER
//  SPATK_COLOR =
//  SPATK_COLOR_HOVER =
//  SPDEF_COLOR =
//  SPDEF_COLOR_HOVER =
//  SPEED_COLOR =
//  SPEED_COLOR_HOVER =

implementation

end.
